services:
  DataBase:
    image: mysql:8.0
    container_name: ${MYSQL_HOST}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./DataBase/data:/var/lib/mysql
      - ./DataBase/scripts:/docker-entrypoint-initdb.d
  backend:
    build: .
    container_name: ${APP_HOST}
    restart: unless-stopped
    ports: 
      - ${APP_PORT}:3010 #Este tiene que ser el mismo que en index.js
    depends_on:
      - DataBase
    volumes:
      - ./:/app
      - node_modules_mydb:/app/node_modules
      
volumes:
  node_modules_mydb: